# -*- coding: utf-8 -*-
"""Python para Dados - Desafio Final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M5Za014EDsymFuIWigba_idYQJyCquv3

Você é uma pesquisadora que está tentando entender melhor qual o impacto
do estilo de vida de uma pessoa na sua qualidade de sono, por isso fez a coleta
dos dados de sobre 373 pessoas, onde foram recolhidas 12 características para
cada uma delas. Por competência a sua pesquisa foi bem controlada e você
não tem dados faltosos na sua base. Chegou o momento de você fazer sua
análise e responder algumas perguntas.
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/saude_do_sono_estilo_vida.csv')

"""1. Ao visualizar a base você percebeu que seria melhor alterar o nome de
algumas colunas. Mude o ‘ID’ para ‘Identificador’, corrija o nome da coluna
que indica a pressão sanguínea, mude a coluna ‘Ocupação’ para ‘Profissão’,
a coluna ‘Categoria BMI’ está em parte em inglês, substitua para ‘Categoria
IMC’.

"""

df

df.columns

novas_cols = {'ID': 'Identificador',
              'Pressão sanguíneaaaa': 'Pressão sanguínea',
              'Ocupação': 'Profissão',
              'Categoria BMI': 'Categoria IMC'
              }

df.rename(columns=novas_cols, inplace=True)
df.head()

"""2. Qual é a média, a moda e a mediana de horas de sono para cada uma
das profissões? [‘mean’, np.median, pd.Series.mode]

"""

#media
df.groupby('Profissão')['Duração do sono'].mean()

#moda
df.groupby('Profissão')['Duração do sono'].agg(pd.Series.mode)

#mediana
df.groupby('Profissão')['Duração do sono'].agg(np.median)

"""3. Das pessoas que atuam com engenharia de software qual a
porcentagem de obesos?

"""

#filtro na tabela para ver apenas engenheiro de software
eng_software = df[df['Profissão'] == 'Eng. de Software']
eng_software

# quantidade total de pessoas com profissão igual a engenheiro de software
total_eng_software = eng_software['Profissão'].shape[0]
total_eng_software

#filtro de pessoas obesas dentro dos engenheiros de software
obesos_eng_software = eng_software[eng_software['Categoria IMC'] == 'Obesidade']
obesos_eng_software

#quantidade de pessoas obesas dentro dos engenheiros de software
total_obeso_eng_software = obesos_eng_software['Categoria IMC'].shape[0]
total_obeso_eng_software

#proporção
porcentagem_obesos = (total_obeso_eng_software / total_eng_software) * 100
porcentagem_obesos

"""4. De acordo com os dados, advogar ou ser representante de vendas faz
você dormir menos? (Use o método ‘isin’, considere a média)
"""

qtdesono = df[df['Profissão'].isin(['Advogado(a)','Representante de Vendas'])]
qtdesono

qtdesono.groupby('Profissão')['Duração do sono'].mean()

"""5. Entre quem fez enfermagem e quem fez medicina, quem tem menos
horas de sono? (Use o método ‘isin’, considere a média)

"""

horassono = df[df['Profissão'].isin(['Enfermeiro(a)','Médico(a)'])]
horassono

horassono.groupby('Profissão')['Duração do sono'].mean()

"""6. Faça um subconjunto com as colunas Identificador, Gênero, Idade,
Pressão sanguínea e Frequência cardíaca.

"""

new_data = df[['Identificador', 'Gênero', 'Idade',
'Pressão sanguínea', 'Frequência cardíaca']]
new_data.head()

"""7. Descubra qual a profissão menos frequente no conjunto. (Use
value_counts)

"""

profissão_sort = df['Profissão'].value_counts(ascending=True)
profissão_sort

print(profissão_sort.index[0])

"""8. Quem tem maior pressão sanguínea média, homens ou mulheres?
(Considere a média)

"""

df.head()

df_pressao = df.copy()

#criação de duas colunas para separar os valores da pressão sanguinea pelo separador '/'
df_pressao[['Sistólica', 'Diastólica']] = df_pressao['Pressão sanguínea'].str.split('/', expand=True).astype(float)
df_pressao.head()

# tirar a media das colunas criadas e gerar mais uma coluna
df_pressao['Pressão sanguínea média'] = df_pressao[['Sistólica', 'Diastólica']].mean(axis=1)
df_pressao.head()

#usando a coluna calculada, agrupando a media por gênero
media_genero = df_pressao.groupby('Gênero')['Pressão sanguínea média'].mean()
media_genero

"""9. É predominante entre os participantes dormir 8 horas por dia
(considere usar Moda como medida)?

"""

participantes = df.groupby('Gênero')['Duração do sono'].agg(pd.Series.mode)
participantes

print('De acordo com a moda, não é comum os participantes dormirem 8 horas por dia')

"""10. Pessoas com frequências cardíacas acima de 70 dão mais passos que
pessoas com frequência cardíaca menor ou igual a 70? (Use a média)
"""

df_copy = df.copy()

df_copy['freq_cardiaca_maior70'] = (df["Frequência cardíaca"] > 70)
df_copy['freq_cardiaca_maior70']

df_copy['freq_cardiaca_menor70'] = (df["Frequência cardíaca"] <= 70)
df_copy['freq_cardiaca_menor70']

#media de passos para frequencia cardiaca maior que 70
media_passos_maior70 = df_copy[df_copy['freq_cardiaca_maior70']==True]['Passos diários'].mean()
media_passos_maior70

#media de passos para frequencia cardiaca menor que 70
media_passos_menor70 = df_copy[df_copy['freq_cardiaca_menor70']==True]['Passos diários'].mean()
media_passos_menor70